[pytest]
markers =
    duckduckgo: marker for DuckDuckGo-related tests
    api: marker for API tests
    ui : marker for UI tests
    saucedemo: marker for tests that run on Sauce Labs
testpaths = tests
